apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7ImF1dGgiOiJSV3RoZEdWeWFXNWhRMmgxZG1GcmFHbHVZVHBuYUhCZldtUnVOM1p6YUZoTlVHRm9OV1Z6T0c1SmJtbFJiV2xJYmpSbldEbFVNVmxGTWxKVCJ9fX0=
type: kubernetes.io/dockerconfigjson
