apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: movies-serivce
spec:
  host: movies-service
  trafficPolicy:
    connectionPool:
      http:
        http1MaxPendingRequests: 1
        maxRequestsPerConnection: 1
      tcp:
        maxConnections: 1
    outlierDetection:
      baseEjectionTime: 3m
      consecutive5xxErrors: 5
      interval: 1s
      maxEjectionPercent: 100